### ISSUE TITLE
Can't use with latest irssi

### ISSUE THREAD

**Issue by coral** [falsovsky/FiSH-irssi#30] opened 2016-01-20 10:41 UTC
```Irssi: fish/fish is ABI version 0 but Irssi is version 1, cannot load```

```Irssi: Client: irssi 0.8.18-g4af3a47 (20160112 2338)```

Is the old ABI interface deprecated or did i build it wrong?

**Comment by falsovsky** [comment] 2016-01-20 11:01
Hi,

I think now irssi requires you to rebuild the modules after updating irssi.
And also requires some new functions i think. I will add it later.

**Comment by coral** [comment] 2016-01-20 12:10
I just built the project from scratch but still same issue so probably some functions.

**Comment by falsovsky** [comment] 2016-01-20 12:25
Later in the day I will comment to this issue, when I'm at home.

**Comment by ailin-nemui** [comment] 2016-01-20 15:03
Hi, we added some compile-time constant to stop irssi from crashing with modules compiled into different irssi versions. To use it, please include

```
#ifdef IRSSI_ABI_VERSION
void //MODULENAME//_abicheck(int *version)
{
    *version = IRSSI_ABI_VERSION;
}
#endif
```
next to your `_init` and `_deinit` functions. sorry for the inconvenience!

**Comment by falsovsky** [comment] 2016-01-20 15:10
Yes, thats what im going to do. And also merge some fixes that are on another branch

**Comment by falsovsky** [comment] 2016-01-20 15:41
Are you sure you rebuild fish after installing that irssi ?

I just installed irssi from git, and then build fish, I cant reproduce that:

15:38 -!-  ___           _
15:38 -!- |_ _|_ _ _____(_)
15:38 -!-  | || '_(_-<_-< |
15:38 -!- |___|_| /__/__/_|
15:38 -!- Irssi v0.8.18-g79fa2fc - http://www.irssi.org
15:39 -!- Irssi: FiSH r212-3682ed8 - encryption module for irssi loaded!
15:39 -!- Irssi: URL: https://github.com/falsovsky/FiSH-irssi
15:39 -!- Irssi: Try /helpfish or /fishhelp for a short command overview
15:39 -!- FiSH: Using default password to decrypt blow.ini... Try /setinipw to set a custom password.
15:39 -!- Irssi: Loaded module fish/core

Can you plz confirm ?

**Comment by ailin-nemui** [comment] 2016-01-20 15:44
g79fa2fc -> is from last year. try updating your irssi.git

**Comment by falsovsky** [comment] 2016-01-20 16:32
I did some fuck up, dont use it as it is now.

**Comment by falsovsky** [comment] 2016-01-20 21:47
Im sorry @ailin-nemui , but when downloading irssi from master, that revision appears on irssi. Or im doing something wrong.

Should I use a different branch?

**Comment by falsovsky** [comment] 2016-01-20 21:48
Maybe the 0.8.18-beta2 tag ?

**Comment by falsovsky** [comment] 2016-01-20 22:05
This is fixed with aede935ef4c364e4ad9546aaf857edc0cc6a242c

Thanks for reporting.
And thanks to @ailin-nemui for helping me out.

**Closed by falsovsky** 2016-01-20 22:05 UTC

**Comment by ailin-nemui** [comment] 2016-01-20 22:08
weird, master should give you -g4af3a47 you can also see it on the website https://github.com/irssi/irssi/commits/master

**Comment by falsovsky** [comment] 2016-01-20 22:11
Yes I know. Its weird, I dont understand it either.
I've used the tag, and it now checks for the abi so I could test :-)

**Comment by falsovsky** [comment] 2016-01-20 22:12
Now i'm going to try to merge a branch that I have, that changes every fixed buffer to use malloc. :-)

**Comment by ailin-nemui** [comment] 2016-01-20 22:12
good luck!

**Comment by coral** [comment] 2016-01-21 16:21
FiSH ERROR: Unable to write new blow.ini, probably out of disc space.

Seems like it can't write this one :(

**Comment by falsovsky** [comment] 2016-01-21 16:24
You get that by doing what ? Typing in the password at startup ?

**Comment by coral** [comment] 2016-01-21 16:30
/setinipw 

Also i must say i am very impressed by how fast you respond! I really like this project a lot.

**Comment by falsovsky** [comment] 2016-01-21 16:36
-bash-4.3$ ls -sl .irssi/blow.ini
4 -rw-r--r--  1 fish  fish  115 Jan 21 16:35 .irssi/blow.ini

What are the permissions on yours ?
Or are you starting without any blow.ini ?

I need to figure out all the steps youre doing to reproduce this problem.

**Comment by coral** [comment] 2016-01-21 20:16
coral@shell:~$ ls -sl .irssi/blow.ini
4 -rw-r--r-- 1 coral coral 26 Jan 21 17:20 .irssi/blow.ini

**Comment by coral** [comment] 2016-01-21 20:17
I started without any blow.ini at first.

**Comment by coral** [comment] 2016-01-21 20:17
coral@shell:~/.irssi$ cat blow.ini 
[FiSH]
ini_password_Hash=

**Comment by falsovsky** [comment] 2016-01-21 20:20
Ok. Thanks, im going to try to reproduce it!

**Comment by falsovsky** [comment] 2016-01-21 20:53
I can reproduce it now. Going to fix it!

**Comment by coral** [comment] 2016-01-21 21:19
Cool! Looking forward to it

**Comment by falsovsky** [comment] 2016-01-21 21:59
Hi,

I think I fixed it now with commit 2b0c1c095035e052afcc27f074cb7b51fb0d669f

git pull again and try it!

The problem was that it was trying to set the inipw for blow.ini but it didnt yet exist.

**Comment by coral** [comment] 2016-01-21 23:21
@falsovsky Fixed! Big thanks!

**Comment by sicko-gl** [comment] 2016-11-24 00:17
Hi, I get the same error.
Compiled irssi 0.8.20 from source, cloned fish-irssi from github and built.

$ uname -a
OpenBSD nightfall.bogus.net 5.9 GENERIC#6 amd64

Running irssi: 
 -!- Irssi: Client: irssi 0.8.20 (20160914 1355)
/load /home/sicko-gl/.irssi/modules/libfish.so
 -!- Irssi: fish/fish is ABI version 0 but Irssi is version 2, cannot load

The file:
-rw-r--r--  1 sicko-gl  users  57019 Nov 22 13:26 /home/sicko-gl/.irssi/modules/libfish.so

Any suggestions?

**Comment by falsovsky** [comment] 2016-11-24 01:19
The problem probably is that you have two versions of the irssi include files.
